### ISSUE TITLE
pterodactyl compatibility

### ISSUE THREAD

**Issue by Kaludii** [tomrhollis/vellum-for-EZ#1]
Hey! I use the pterodactyl and the startup command for the .exe doesn't work. Could you add compatibility to use this with pterodactyl?

**Comment by clarkx86** [comment]
I haven't used Pterodactyl yet, but can you change the startup command? What is the current startup command set to?

**Comment by Kaludii** [comment]
> I haven't used Pterodactyl yet, but can you change the startup command? What is the current startup command set to?
> 
> *EDIT*: From my very quick research , I saw that Pterodactyl uses Docker for the server instances (correct me if I'm wrong). Make sure the .NET Core runtime is installed in the Docker container.

I'm pretty sure it is installed on my VPS! And the startup command is wine64 bedrock_server_mod.exe but when I change it to the new .exe it crashes the panel, and doesn't start

**Comment by clarkx86** [comment]
Before running vellum it needs to be configured so it points to the `bedrock_server_mod.exe` executable. In the directory where the vellum executable is located should be a `configuration.json`, which you should configure according to your needs. You can see an overview [here](https://github.com/clarkx86/vellum#configuration-overview).

**Comment by Kaludii** [comment]
> Before running vellum it needs to be configured so it points to the `bedrock_server_mod.exe` executable, or else it will just exit. In the directory where the vellum executable is located should be a `configuration.json`, which you should configure according to your needs. You can see an overview [here](https://github.com/clarkx86/vellum#configuration-overview).

Thanks for this! I acctually switched over to windows, but everytime I try running the .exe, it comes up with this errro 
![image](https://user-images.githubusercontent.com/63890666/88485712-93eda080-cf3d-11ea-82d4-9a6d3b11a823.png)
Failed to load symbols from maInjected!
in executable!
The specified procedure could not be found.
Any ideas?

**Comment by clarkx86** [comment]
Unfortunately I can't help you with that because I don't have any experience with EZ, but maybe @tomrhollis has an idea? :slightly_smiling_face:

**Comment by tomrhollis** [comment]
Github noob here, looks like I set something up wrong so posts here go to Clark instead of me.  Sorry about that, I got no notification of this until he tagged me.

I've seen that error before, it's signalling a problem with the setup of ElementZero itself not a vellum issue.  But I can't remember exactly how I fixed EZ from there unfortunately.  It was either that one of the EZ DLLs was missing, or the version of EZ was mismatched from the version of BDS (I had both of those problems around the same time).

**Comment by Kaludii** [comment]
> Github noob here, looks like I set something up wrong so posts here go to Clark instead of me.  Sorry about that, I got no notification of this until he tagged me.
> 
> 
> 
> I've seen that error before, it's signalling a problem with the setup of ElementZero itself not a vellum issue.  But I can't remember exactly how I fixed EZ from there unfortunately.  It was either that one of the EZ DLLs was missing, or the version of EZ was mismatched from the version of BDS (I had both of those problems around the same time).

Oh! Would you be able to send me the .dll's for your EZ if you don't mind?

**Comment by tomrhollis** [comment]
Sure see attached here for the DLLs that go in the root folder.  These are from the June 26 release (https://github.com/Element-0/ElementZero/releases/tag/200626) so if things still aren't working, check out that download there, maybe start over with that.

Will close this for now but if anything comes up that's likely a vellum issue please post again! (note that I will probably be remaking this fork from scratch tomorrow to fix the notification issues)

[EZdlls.zip](https://github.com/tomrhollis/vellum-for-EZ/files/4979878/EZdlls.zip)
